- hosts: frontends
  gather_facts: false
  tasks:
  
  - name: Curl website
    command: curl "http://frontend1.{{ ANSIBLE_ADVANCE_GUID }}.example.opentlc.com"
    register: webpage
  
  - debug: var=webpage.stdout
  
  - name: Fail
    fail:
    when: "'Ansible' not in webpage.stdout"
  
  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"

