---
# vars file for osp.servers
osp_servers:
  frontend:
    name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: frontend
    networks: 
     int: int_network
     ext: ext_network
    meta:
     group: frontends 
     deployment_name: QA
  app1:
    name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    networks:
     int: int_network 
     ext: ext_network
    meta:
     group: apps
     deployment_name: QA
  app2:
    name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: apps
    networks:
     int: int_network
     ext: ext_network
    meta:
     group: apps
     deployment_name: QA
  db:
    name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m2.small
    security_group: db
    networks:
     int: int_network
     ext: ext_network
    meta:
     group: appdbs 
     deployment_name: QA

