---
# tasks file for aws-creds
  - name: Install required packages 
    yum: 
     name: "{{item}}"
     state: latest 
    loop: 
      - python 
      - python-pip 
      - python-devel 
      - gcc

  - name: Install tower-cli
    pip:
     name: ansible-tower-cli
     state: latest

  - name: List key files
    shell: (cd /root/.ssh; find . -maxdepth 1 -type f -iname '*key.pem')| cut -d'/' -f2
    register: file_to_copy

  - name: Tower Creds key file
    tower_credential:
      name: Creds for AWS instances
      organization: Default
      state: present
      kind: ssh
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      tower_verify_ssl: no
      ssh_key_data: "/root/.ssh/{{ file_to_copy.stdout }}"
      username: ec2-user

  - name: Update Prod Job template
    tower_job_template:
      name: "3 tier app on Prod"
      credential: "Creds for AWS instances"
      vault_credential: "yum-repo-cred"
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      tower_verify_ssl: no
      state: present
      job_type: run
      playbook: site-3tier-app.yml
      project: "Homework Assignment"

  - name: Update Prod Smoke Job template
    tower_job_template:
      name: "Smoke test Prod env"
      credential: "Creds for AWS instances"
      vault_credential: "yum-repo-cred"
      tower_host: "{{ tower_host }}"
      tower_username: "{{ tower_username }}"
      tower_password: "{{ tower_password }}"
      tower_verify_ssl: no
      state: present
      job_type: run
      playbook: site-smoketest-aws.yml
      project: "Homework Assignment"

  #- name: Update inventory groups
  #  shell: |
  #   tower-cli group associate  --group tag_AnsibleGroup_bastions  --parent bastions --inventory "Three tier inventory"
  #   tower-cli group associate  --group "tag_AnsibleGroup_appdbs"  --parent "appdbs" --inventory "Three tier inventory"
  #   tower-cli group associate  --group "tag_AnsibleGroup_apps"  --parent "apps" --inventory "Three tier inventory"
  #   tower-cli group associate  --group "tag_AnsibleGroup_frontends"  --parent "frontends" --inventory "Three tier inventory"
