- name: Create Homework Assignment project 
  # Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  tower_project:
   name: "{{proj_name}}"
   organization: "{{org_name}}"
   scm_type: git
   scm_url: "{{scm_url}}"
   scm_branch: "{{scm_branch}}"
   state: present
   tower_host: tower1.{{tower_GUID}}.example.opentlc.com
   tower_username: "{{user_name}}"
   tower_password: "{{password}}"
   tower_verify_ssl: no

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: "{{ssh_cred_name}}"
    organization: "{{org_name}}"
    state: present
    kind: ssh
    ssh_key_data: "{{user_cred_path}}"
    username: "{{user_cred_name}}"
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{user_name}}"
    tower_password: "{{password}}"
    tower_verify_ssl: no

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name {{group_name}}

- name: Add workstation host in tower_inventory 
  command: |
    tower-cli host create --inventory "{{static_inventory_name}}" --name "{{host_name}}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{org_name}}"
    state: present
    kind: ssh
    ssh_key_data: "{{opentlc_cred_path}}"
    username: "{{opentlc_login}}"
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
    tower_username: "{{user_name}}"
    tower_password: "{{password}}"
    tower_verify_ssl: no

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

