---
# tasks file for db-tier
- name: Install PostgreSQL`
  yum:
   name: postgresql-server
   state: present
  tags:
   - dbs
   - postgres

- name: Check if PostgreSQL database is initialized
  command: postgresql-check-db-dir /var/lib/pgsql/data
  register: a_pg_data_dir
  changed_when: a_pg_data_dir == 1
  ignore_errors: yes
  tags:
   - dbs
   - postgres

- name: Ensure PostgreSQL database is initialized.
  shell: postgresql-setup initdb
  when: a_pg_data_dir.rc != 0
  tags:
   - dbs
   - postgres

- name: Start PostgreSQL
  service:
   name: postgresql
   state: started
   enabled: yes
  tags:
   - dbs
   - postgres

